services:
  - type: web
    name: jom-makan
    plan: starter
    env: python
    region: singapore
    buildCommand: "cd django-app && ./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: jom_makan_pg
  - region: singapore
  - plan: starter
  - databaseName: jom_makan_db