services:
  - type: web
    name: jom-makan
    plan: starter
    env: python
    region: Singapore  # region should be same as your database region.
    buildCommand: "/django-app/build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
